# Generated by Django 6.0.3 on 2026-04-20 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ratings.rating'),
        ),
    ]
