# Generated by Django 6.0.3 on 2026-04-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
