# Generated by Django 6.0.3 on 2026-04-01 12:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='follower_user_id',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='following_user_id',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower_user_id', 'following_user_id')},
        ),
    ]
