# Generated by Django 6.0.3 on 2026-04-01 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_rename_follower_follow_follower_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower_user_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following_user_id',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
